version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq1'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq2'
      RABBITMQ_USE_LONGNAME: 'true'
    depends_on:
      - rabbitmq1
    links:
      - rabbitmq1
    ports:
      - '15673:15672'
      - '5673:5672'
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    command: >
      sh -c "
        rabbitmq-server &
        sleep 30 &&
        rabbitmqctl stop_app &&
        rabbitmqctl join_cluster rabbit@rabbitmq1 &&
        rabbitmqctl start_app &&
        tail -f /dev/null
      "

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq3'
      RABBITMQ_USE_LONGNAME: 'true'
    depends_on:
      - rabbitmq1
    links:
      - rabbitmq1
    ports:
      - '15674:15672'
      - '5674:5672'
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
    command: >
      sh -c "
        rabbitmq-server &
        sleep 30 &&
        rabbitmqctl stop_app &&
        rabbitmqctl join_cluster rabbit@rabbitmq1 &&
        rabbitmqctl start_app &&
        tail -f /dev/null
      "

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:

